apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-15T21:09:10Z"
  labels:
    app: red
  name: red
  namespace: default
  resourceVersion: "345097"
  uid: f536e207-0aa3-468d-95d8-be597eabd7b0
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.96.9.219
  clusterIPs:
  - 10.96.9.219
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30090
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: red
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
