apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-reader
  namespace: observability-layer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-reader
  namespace: server-layer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-reader
  namespace: client-layer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-reader
subjects:
  - kind: ServiceAccount
    name: pod-reader
    namespace: observability-layer
  - kind: ServiceAccount
    name: pod-reader
    namespace: server-layer
  - kind: ServiceAccount
    name: pod-reader
    namespace: client-layer
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
