kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 8080
        hostPort: 8080
        protocol: TCP
      - containerPort: 3000
        hostPort: 3000
        protocol: TCP
      - containerPort: 30030
        hostPort: 30030
        protocol: TCP
      - containerPort: 30081
        hostPort: 30081
        protocol: TCP
      - containerPort: 30529
        hostPort: 30529
        protocol: TCP
      - containerPort: 30859
        hostPort: 30859
        protocol: TCP
      - containerPort: 32250
        hostPort: 32250
        protocol: TCP
