apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-reader
  namespace: profile-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: profile-service
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader
  namespace: profile-service
subjects:
  - kind: ServiceAccount
    name: pod-reader
    namespace: profile-service
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
