apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-client
  namespace: profile-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-client
  template:
    metadata:
      labels:
        app: profile-client
    spec:
      containers:
        - name: client
          image: profile-client:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: API_URL
              value: "http://profile-service:8080"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: profile-client
  namespace: profile-service
spec:
  selector:
    app: profile-client
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
