apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init
  namespace: profile-service
data:
  init.js: |
    // Create admin user
    db = db.getSiblingDB("admin");
    db.createUser({
      user: "admin",
      pwd: "admin123",
      roles: [
        { role: "userAdminAnyDatabase", db: "admin" },
        { role: "readWriteAnyDatabase", db: "admin" },
      ],
    });

    // Create profile service user
    db = db.getSiblingDB("profile_service");
    db.createUser({
      user: "profile",
      pwd: "profile123",
      roles: [{ role: "readWrite", db: "profile_service" }],
    });
