apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-worker
  template:
    metadata:
      labels:
        app: profile-worker
    spec:
      containers:
        - name: worker
          image: profile-server:latest
          imagePullPolicy: Never
          command: ["./server", "worker"]
          env:
            - name: MONGODB_URI
              value: "mongodb://mongodb:27017"
            - name: REDIS_ADDR
              value: "redis:6379"
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@rabbitmq:5672/"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            exec:
              command: ["pgrep", "server"]
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["pgrep", "server"]
            initialDelaySeconds: 5
            periodSeconds: 5
