apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-worker
  namespace: profile-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: profile-worker
  template:
    metadata:
      labels:
        app: profile-worker
    spec:
      containers:
        - name: profile-worker
          image: profile-worker:latest
          imagePullPolicy: Never
          env:
            - name: RABBITMQ_URI
              value: "amqp://user:password@rabbitmq.profile-service.svc.cluster.local:5672/"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
