apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: profile-service
data:
  mongodb-uri-template: "mongodb://$(MONGODB_USERNAME):$(MONGODB_PASSWORD)@mongodb:27017/admin?authSource=admin"

apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init
  namespace: profile-service
data:
  init.js: |
    // Create admin user
    db = db.getSiblingDB('admin');
    db.createUser({
        user: 'admin',
        pwd: 'admin123',
        roles: ['root']
    });

    // Create profile user
    db = db.getSiblingDB('profiles');
    db.createUser({
        user: 'profile',
        pwd: 'profile123',
        roles: [{ role: 'readWrite', db: 'profiles' }]
    });
